language: cpp

compiler:
    - clang
    - gcc

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

before_install:

    - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y ppa:h-rayflood/llvm

    - sudo apt-get update -qq

install:

    - sudo apt-get install cmake cmake-data

    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - sudo apt-get install --allow-unauthenticated -qq clang-3.4
    - export CXX="clang++-3.4"

script:
    - scripts/rebuild.sh
    - build/bin/runBasicTests