language: cpp

compiler:
    - clang
    - gcc

before_install:

    - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y ppa:h-rayflood/llvm

    - sudo apt-get update -qq

install:

    - sudo apt-get install cmake cmake-data

    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - sudo apt-get install --allow-unauthenticated -qq clang-3.4
    - export CXX="clang++-3.4"

sudo: required
script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - mkdir build
  - cd build
  - cmake ..
  - make
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5